name: Kirim Notifikasi Harian

on:
  schedule:
    # Mengatur waktu kirim (Jam 00:00 WITA / 16:00 UTC setiap hari)
    - cron: '0 16 * * *'

jobs:
  kirim-notif:
    runs-on: ubuntu-latest
    steps:
      - name: Panggil API OneSignal
        run: |
          curl --request POST \
            --url https://onesignal.com/api/v1/notifications \
            --header "Authorization: Basic ${{ secrets.ONESIGNAL_REST_API_KEY }}" \
            --header "Content-Type: application/json" \
            --data '{
              "app_id": "${{ secrets.ONESIGNAL_APP_ID }}",
              "included_segments": ["Subscribed Users"],
              "contents": {"en": "Lihat rekab pertandingan hari ini di MASTERLAGA!"},
              "headings": {"en": "Update MASTERLAGA"}
            }'
